import { StyleSheet } from 'react-native';
import { Colors, GlassTokens } from './colors';

export const GlobalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background.primary,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: Colors.text.primary,
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.text.secondary,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: Colors.text.primary,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.text.primary,
  },
  body: {
    fontSize: 14,
    fontWeight: '400',
    color: Colors.text.primary,
    lineHeight: 20,
  },
  caption: {
    fontSize: 12,
    fontWeight: '500',
    color: Colors.text.secondary,
  },
  label: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  card: {
    backgroundColor: Colors.card.white,
    borderRadius: 16,
    padding: GlassTokens.spacing.lg,
    shadowColor: Colors.card.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.card.borderLight,
  },
  cardLarge: {
    backgroundColor: Colors.card.white,
    borderRadius: 20,
    padding: GlassTokens.spacing.lg,
    shadowColor: Colors.card.shadowLg,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 1,
    borderColor: Colors.card.borderLight,
  },
  buttonPrimary: {
    backgroundColor: Colors.primary.main,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 48,
    shadowColor: Colors.glow.indigo,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 4,
  },
  buttonSecondary: {
    backgroundColor: Colors.background.secondary,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border.light,
    paddingVertical: 12,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 48,
  },
  buttonSuccess: {
    backgroundColor: Colors.success.main,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 48,
    shadowColor: Colors.glow.green,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 4,
  },
  buttonDanger: {
    backgroundColor: Colors.danger.main,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 48,
    shadowColor: Colors.glow.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 4,
  },
  buttonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#ffffff',
  },
  buttonTextSecondary: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.primary.main,
  },
  input: {
    backgroundColor: Colors.background.secondary,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border.light,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 15,
    color: Colors.text.primary,
    minHeight: 48,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeSuccess: {
    backgroundColor: Colors.success.lightest,
    borderWidth: 1,
    borderColor: Colors.success.lighter,
  },
  badgeWarning: {
    backgroundColor: Colors.warning.lightest,
    borderWidth: 1,
    borderColor: Colors.warning.lighter,
  },
  badgeDanger: {
    backgroundColor: Colors.danger.lightest,
    borderWidth: 1,
    borderColor: Colors.danger.lighter,
  },
  badgePrimary: {
    backgroundColor: Colors.primary.lightest,
    borderWidth: 1,
    borderColor: Colors.primary.lighter,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.text.primary,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.border.light,
    marginVertical: GlassTokens.spacing.md,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  section: {
    padding: GlassTokens.spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: GlassTokens.spacing.lg,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.text.primary,
  },
  sectionLink: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.primary.main,
  },
});

export const GradientsStyle = {
  primary: {
    colors: ['#6366F1', '#4F46E5'],
    start: { x: 0, y: 0 },
    end: { x: 1, y: 1 },
  },
  success: {
    colors: ['#34D399', '#10B981'],
    start: { x: 0, y: 0 },
    end: { x: 1, y: 1 },
  },
  warning: {
    colors: ['#FBBF24', '#F59E0B'],
    start: { x: 0, y: 0 },
    end: { x: 1, y: 1 },
  },
  danger: {
    colors: ['#F87171', '#EF4444'],
    start: { x: 0, y: 0 },
    end: { x: 1, y: 1 },
  },
};
