"""Add name column to staff table

Revision ID: 575e03e381d5
Revises: 83c50792aab3
Create Date: 2025-04-30 14:16:20.334663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575e03e381d5'
down_revision = '83c50792aab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        # Add 'name' column with a default empty string
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        # Remove 'name' column during downgrade
        batch_op.drop_column('name')

    # ### end Alembic commands ###
