"""Add location columns to attendance tables

Revision ID: f9d791e66671
Revises: 9a7c3f5e2b1d
Create Date: 2026-03-28 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d791e66671'
down_revision = '9a7c3f5e2b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add location columns to attendance_photos table
    try:
        op.add_column('attendance_photos', sa.Column('latitude', sa.Float(), nullable=True))
        op.add_column('attendance_photos', sa.Column('longitude', sa.Float(), nullable=True))
        op.add_column('attendance_photos', sa.Column('location_accuracy', sa.Float(), nullable=True))
    except Exception as e:
        print(f"Note: Location columns already exist in attendance_photos: {e}")

    # Add location columns to attendance_records table
    try:
        op.add_column('attendance_records', sa.Column('latitude', sa.Float(), nullable=True))
        op.add_column('attendance_records', sa.Column('longitude', sa.Float(), nullable=True))
        op.add_column('attendance_records', sa.Column('location_accuracy', sa.Float(), nullable=True))
    except Exception as e:
        print(f"Note: Location columns already exist in attendance_records: {e}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove location columns from attendance_records table
    op.drop_column('attendance_records', 'location_accuracy')
    op.drop_column('attendance_records', 'longitude')
    op.drop_column('attendance_records', 'latitude')

    # Remove location columns from attendance_photos table
    op.drop_column('attendance_photos', 'location_accuracy')
    op.drop_column('attendance_photos', 'longitude')
    op.drop_column('attendance_photos', 'latitude')

    # ### end Alembic commands ###
